### ISSUE TITLE
User can save a note.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/web-api#1]
# Motivation

Before notes can be displayed, users must be able to submit a note.

# Tasks

- [x] Create a working file server that takes POST requests
    - [x] Create an index.js file to house the file server and save the required packages into variables.
    - [x] Add an event handler to listen on port 3000 for http requests.
    - [x] Use body parser to convert request body into JSON
    - [x] Create an event handler to deal with POST requests
    - [x] Add contents of POST requests to text file along with instantiated id.
    - [x] Respond to POST with appropriate status code.
