### ISSUE TITLE
User can delete a note by id.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/web-api#4]
# Motivation

In addition to updating the contents of one or more notes, users should be able to delete a note selected via its unique id.

# Tasks

- [x] Add an event handler for DELETE requests, selecting a note via id parameter in URL
- [x] Remove selected note from notes array within event handler
- [x] Respond to request with status 204 - No Content
